### ISSUE TITLE
CSS NextJS issue

### ISSUE THREAD

**Issue by adventurini** [Neighbor-Army/help-with-covid#30]
I have encountered this issue quite a bit where the HTML does not ship with CSS in next.

**Reproduce**
- It's fairly hard to reproduce on purpose, but it happens quite often. The bug will come and go once the site has cached.

**Possible Fixes**
- I believe that it is just a CSS structuring issue. If we pull in the each CSS into the index file I believe it should be solved.

**Comment by Hotaman** [comment]
Does the problem manifest as a flash without CSS or is it a different problem?

**Comment by rluvaton** [comment]
@adventurini Why did you close this issue, the PR not merged yet
