### ISSUE TITLE
Commit message enforcement idea

### ISSUE THREAD

**Issue by rluvaton** [Neighbor-Army/help-with-covid#42]
I think we should add a commit convention like [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

what do you think?

**Comment by hjhart** [comment]
Huh! I've never used that for on a team, but it looks pretty good. I'm sure it'll bug some people when it slows them down. 

Automated conventions are probably a good thing for open source work where it's hard to onboard people.

I'm on the fence about whether or not to do it but, if people feel strongly I'm up for it.

**Comment by adventurini** [comment]
We could enforce gitmoji. It sort of handles that thing for you and it prettifies repos.

**Comment by rluvaton** [comment]
I think that this would help for better understanding commits, generating a changelog and auto-deploy based on the commits types (feature / hotfix /etc...)

**Comment by rluvaton** [comment]
@Miikis What do you think?

**Comment by Miikis** [comment]
Not sure about this. Aside from the consistency benefits — the same ones for eslint and prettier and husky and lint-staged — how does this help if you don't have CD/CI setup? Seems like a less opinionated alternative is to keep utilizing GitHub's PR workflow but keep the PRs as focused as possible. I'd say that before we start worrying about consistent commit formatting, we should enforce the original branching workflow we agreed to; finish setting up CD/CI; add more tests for the serverless functions; and add more tests for the frontend.
